version: "3.9"
services:
  node-api:
    image: ghcr.io/henriteinturier/projet2-cicd-final/node-api:main
  frontend:
    image: ghcr.io/henriteinturier/projet2-cicd-final/frontend:main
  cypress:
    image: cypress/included
    working_dir: /e2e
    volumes:
      - ./frontend:/e2e
    entrypoint: cypress run  --config baseUrl=http://frontend --headless --browser chrome
    depends_on:
      - frontend
      - node-api
