name: CI/CD workflow

on:
  push:
    branches:
      - main

jobs:
  build-frontend-and-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - context_name: frontend
            image_name: ghcr.io/henriteinturier/projet2-cicd-final/frontend
          - context_name: node-api
            image_name: ghcr.io/henriteinturier/projet2-cicd-final/node-api
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image_name }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.context_name  }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,name=cache
