name: Develop Branch Workflow

concurrency:
  group: develop-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - develop

jobs:
  develop-tests-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: "./frontend/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Run Linter
        run: npm run lint
      - name: npm audit
        run: npm audit --production --audit-level=high

  develop-tests-node-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./node-api
    strategy:
      fail-fast: true
      matrix:
        npm_commande:
          [
            "run test:ci",
            "run lint",
            "audit --production --audit-level=critical",
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: "./node-api/package-lock.json"
      - name: Install dependencies
        run: npm ci
      - name: Lancer les tests
        run: npm ${{ matrix.npm_commande }}
