name: e2e-production-tests

on:
  workflow_call:
    secrets:
      SERVER_PRODUCTION_IP:
        required: true

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    environment:
      name: production-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker images
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-cypress-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-cypress-
      - name: Pull Cypress image
        run: docker pull cypress/included:latest
      - name: Lancement des tests e2e
        run: docker run --rm -v ${{ github.workspace }}/frontend:/e2e -w /e2e cypress/included:latest cypress run --config baseUrl=http://${{ secrets.SERVER_PRODUCTION_IP }} --headless --browser chrome
